- app/components/chat/BaseChat.tsx
We can do a lot more on model selection, just using ollama to give us a list of available local models will be a nice next step.
In the meantime here's a selector to filter down the static model list by providers
Enjoy.
> Add provider filtering on model list

- .env.example
- app/lib/.server/llm/api-key.ts
- app/lib/.server/llm/model.ts
- app/utils/constants.ts
- package.json
- pnpm-lock.yaml
Add ability to use mistral models. @coleam00
> Add mistral models.

- app/utils/constants.ts
- app/utils/types.ts
This pull request introduces improvements to the Ollama model integration and refines type definitions for better type safety and clarity. The changes are primarily focused on the `constants.ts` and `types.ts` files.
Key Changes:
1. In `constants.ts`:
- Updated imports to include `OllamaApiResponse` and `OllamaModel` types.
- Modified the `getOllamaModels` function to use the newly defined types.
- Improved type safety by specifying the response type as `OllamaApiResponse`.
- Updated the model mapping to use the `OllamaModel` type instead of `any`.
2. In `types.ts`:
- Made the `OllamaModel` interface exportable by adding the `export` keyword.
- This change allows the interface to be imported and used in other parts of the application, enhancing type consistency across the project.
These …
> Enhance Ollama Model Integration and Type Definitions

- app/components/workbench/FileTree.tsx
not much to say on this, this was bothering me for a long time with longer list of files
here is a preview
https://github.com/user-attachments/assets/9e970750-ba98-46df-8cc5-92863ab6f7a1
> fix: added scroll fix for file browser

- .env.example
- README.md
- app/lib/.server/llm/api-key.ts
- app/lib/.server/llm/constants.ts
- app/lib/.server/llm/model.ts
- app/lib/.server/llm/stream-text.ts
- app/utils/constants.ts
- app/utils/types.ts
- package.json
- pnpm-lock.yaml
This pull request introduces the integration of Cohere AI models into the project by adding API key management and model retrieval functionalities. The changes allow users to seamlessly connect with Cohere's services and utilize their suite of models.
1. **Environment Variables**  
- Added support for the `COHERE_API_KEY` environment variable.  
- Included instructions on obtaining the API key from Cohere's [dashboard](https://dashboard.cohere.com/api-keys).
2. **Cohere Model Management**  
- Implemented a function `getCohereAIModel(apiKey: string, model: string)` to retrieve specified Cohere AI models using their API.
- Integrated with `@ai-sdk/cohere`.
3. **Static Model Definitions**  
- Defined a list of static models available through Cohere:
- `Command R Plus Latest`
- `Command R …
> Cohere support added

- app/components/chat/APIKeyManager.tsx
- app/components/chat/BaseChat.tsx
- app/components/chat/Messages.client.tsx
- app/components/header/HeaderActionButtons.client.tsx
- app/components/workbench/Workbench.client.tsx
- app/lib/hooks/index.ts
- app/lib/hooks/useViewport.ts
_**NOTE:** First top right expand button is being disabled on mobile as it the container is already 100% in width._
https://github.com/user-attachments/assets/0c217c32-797b-41ab-9009-2fe3bb118715
> fix(ui): mobile friendly

- app/components/chat/BaseChat.tsx
- app/lib/runtime/action-runner.ts
- app/utils/constants.ts
This pull request includes several changes aimed at improving code quality by removing unused variables and adding error logging. The most important changes are grouped by theme:
* Removed the unused `providerList` variable from `app/components/chat/BaseChat.tsx`.
* Added error logging in the `getOllamaModels` function in `app/utils/constants.ts` to provide better debugging information.
* Added error logging in the `getOpenAILikeModels` function in `app/utils/constants.ts` to provide better debugging information.
* Added error logging in the `getLMStudioModels` function in `app/utils/constants.ts` to provide better debugging information.
* Removed an unnecessary return statement in the `ActionRunner` class in `app/lib/runtime/action-runner.ts` to improve code consistency.
> fix: silent eslint issues

- app/utils/constants.ts
Fixes bug with Ollama not respecting model selection
> Ollama not respecting model selection

- vite.config.ts
added the v3_lazyRouteDiscovery flag to solve the warning
> Fixed v3_lazyRouteDiscovery flag warn

- .github/ISSUE_TEMPLATE/bug_report.yml
Updated the issue template to include:
A provider used
A model used
> doc: Issue Template Update

- app/components/chat/Artifact.tsx
Hot fix for artifact bug occurred due to #504
> fix: artifact bugfix

- app/commit.json
- app/components/git/GitUrlImport.client.tsx
- app/routes/git.tsx
https://github.com/user-attachments/assets/c91d4da5-5adc-4bda-9925-701c3d60caa3
> Git import from url

- app/utils/constants.ts
Google just updated their experimental model
> Update to Gemini exp-1206

- docs/docs/index.md
Removed the ollama ModelFile section as it is not needed anymore
> docs: Removed Ollama Modelfile Section

- app/components/settings/SettingsWindow.tsx
Moved Ollama, LM Studio and OpenAI Like to experimental
Fixed toggles not showing in features
Experimental Features Now Work
> ui: Fix Features Toggle

- app/components/chat/BaseChat.tsx
- app/components/chat/ModelSelector.tsx
- app/utils/constants.ts
console error fix due to duplicate keys and logs cleanup
> chore: console error fix due to duplicate keys and logs cleanup

- docs/mkdocs.yml
> fix docs Title

- app/components/settings/SettingsWindow.tsx
Now that Docs are done building here is the change to the new URL
> Changed Docs URL In Settings

- app/components/chat/BaseChat.tsx
- app/components/chat/Chat.client.tsx
- app/components/settings/SettingsWindow.tsx
- app/components/settings/chat-history/ChatHistoryTab.tsx
- app/components/settings/connections/ConnectionsTab.tsx
- app/components/settings/debug/DebugTab.tsx
- app/components/settings/features/FeaturesTab.tsx
- app/components/settings/providers/ProvidersTab.tsx
- app/lib/.server/llm/model.ts
- app/lib/.server/llm/stream-text.ts
- app/lib/hooks/useSettings.tsx
- app/lib/stores/settings.ts
- app/routes/api.chat.ts
- app/routes/api.enhancer.ts
- app/types/model.ts
- app/utils/constants.ts
- app/utils/types.ts
refactored Setting component, added useSettings Hook to get settings details from one single place.
Need to test the base url for local models
> refactor: refactored Setting component, added useSettings Hook to get settings details from one single place.

- CONTRIBUTING.md
- FAQ.md
Remove additional oTToDev mentions
> Remove other oTToDev mentions

- app/utils/constants.ts
Add new google Gemini 2.0 Flash model
> Add gemini flash 2.0

- app/lib/.server/llm/prompts.ts
Fixed some minor grammatical errors and typos in the system prompt.
> fix: grammar/typos in system prompt

- package.json
fix for this issue 
https://thinktank.ottomator.ai/t/bug-in-current-main-branch/2339
> fix: dev command

- app/lib/stores/settings.ts
> fix: added default value to true for provider setting in initial 

- .github/workflows/update-stable.yml
- package.json
This PR introduces an automated release workflow that manages our stable branch, versioning, and changelog generation automatically.
- Automatic version bumping based on PR labels:
- `major` label: Breaking changes (1.0.0 → 2.0.0)
- `minor` label: New features (1.0.0 → 1.1.0)
- No label: Patch fixes (1.0.0 → 1.0.1)
- Automated stable branch management:
- Updates stable branch when PRs with `stable-release` label are merged
- Creates git tags for each release
- Creates GitHub releases
- Automated changelog generation:
- Categorizes changes based on conventional commit types
- Links PRs in changelog entries
- Provides version comparison links
- Groups changes by type (features, fixes, etc.)
1. Follow conventional commits for your commits:
```bash
feat: add new feature
fix: resolve bug
docs: …
```
> chore: Add Automated Release Workflow

- .github/workflows/update-stable.yml
This PR introduces an automated release workflow that manages our stable branch, versioning, and changelog generation automatically.
- Automatic version bumping based on PR labels:
- `major` label: Breaking changes (1.0.0 → 2.0.0)
- `minor` label: New features (1.0.0 → 1.1.0)
- No label: Patch fixes (1.0.0 → 1.0.1)
- Automated stable branch management:
- Updates stable branch when PRs with `stable-release` label are merged
- Creates git tags for each release
- Creates GitHub releases
- Automated changelog generation:
- Categorizes changes based on conventional commit types
- Links PRs in changelog entries
- Provides version comparison links
- Groups changes by type (features, fixes, etc.)
1. Follow conventional commits for your commits:
```bash
feat: add new feature
fix: resolve bug
docs: …
```
> chore:  fix versioning workflow

- .github/workflows/update-stable.yml
Fixing the permission issue in stable release workflow
> fix: the creds issue in workflow

- .github/workflows/update-stable.yml
> chore: fix workflow permission

- .github/workflows/update-stable.yml
- app/commit.json
final fix for automatic versioning
> chore: Versioning workflow

- .github/workflows/update-stable.yml
> chore: Versioning workflow fix

- .github/workflows/update-stable.yml
added workflow permission to workflow
> chore: added workflow permission

- .github/workflows/update-stable.yml
- docs/mkdocs.yml
> docs: added socials

- .github/workflows/pr-release-validation.yaml
- .github/workflows/update-stable.yml
Adding automatic versioning workflow
> chore: Adding workflow

- .github/workflows/commit.yaml
- .github/workflows/update-stable.yml
making commit hash and versioning work together
> chore: skipping commit version

- app/components/chat/ModelSelector.tsx
fix for issue mentioned in thread of #664
> fix: auto select model on provider disabled

- .gitignore
- app/commit.json
Added the app/commit.json file to the .gitignore
> fix: commit file ignore

- app/utils/constants.ts
LM Studio was not able to send a message now it is.
> fix: LM Studio sending message

- app/components/settings/connections/ConnectionsTab.tsx
Here is the preview 
https://github.com/user-attachments/assets/42a3ecf8-395a-4706-9033-ac0b7b9b9db3
> added support for private github repo through github connections

- app/components/chat/BaseChat.tsx
When I entered text using the input method, I found that it conflicted with the textarea submission when I pressed enter, so I dealt with it.
https://github.com/user-attachments/assets/267b4d20-e410-4cab-9dd6-5e9810937c38
> fix: handle conflicts between input method engine and enter key

- CONTRIBUTING.md
- FAQ.md
- README.md
changed Bolt.diy to bolt.diy
reworded the bottom of the README
> doc: README, FAQ, CONTRIBUTING branding updates

- app/components/chat/BaseChat.tsx
changed prompt enhanced to give a toast notification instead of changing the ui.
> ui-ux: prompt enhanced toast notification

- app/components/settings/features/FeaturesTab.tsx
On feature tab: 
Change 'Enable Local Models' to 'Experimental Providers'
Combined (Debug Info and Event Logs) into 'Debug Features'
> ui-ux: Features Tab Changes

- docs/mkdocs.yml
> doc: update mkdocs.yml

- docs/docs/CONTRIBUTING.md
- docs/docs/index.md
used a consistent style throughout the mkdoc's when separating sections (same as the README now).
> doc: mkdoc consistent style

- docs/docs/index.md
> doc: new section heading

- docs/docs/FAQ.md
added information to FAQ in docs on miniflare and wrangler errors in windows
> docs: miniflare and wrangler error

- app/commit.json
- app/routes/api.enhancer.ts
Prompt Enhance option stopped, this fixes it
https://github.com/user-attachments/assets/bb1689d0-890e-42a2-8c68-415287125c9e
> fix: prompt enhance fixed

- FAQ.md
- README.md
- docs/docs/FAQ.md
Updating documentation to include recommended models, an answer to the access violation issue, and a link to the experimental bolt.diy Expert agent on the Live Agent Studio.
> chore: a few documentation enhancements for main README and FAQs

- app/utils/constants.ts
> feat: add xAI grok-2-1212 model

- .github/workflows/docs.yaml
updated the docs ci to only trigger if docs contents changed
> ci: updated the docs ci to only trigger if docs contents changed

- vite.config.ts
hotfix for version metadata variable name issue
> fix: hotfix for version metadata variable name issue 

- app/lib/hooks/useSettings.tsx
fix ghost providers on the chat menu reported by @aliasfoxkde
> fix: provider menu dropdown fix (ghost providers)

- app/lib/modules/llm/providers/ollama.ts
ollama provider module base url hotfix for docker setup
> fix: ollama provider module base url hotfix for docker

- .env.example
many people facing issue due to the IPV6 conversion of localhost to ::1:11434 
so in example I mentioned to use 127.0.0.1 insted of localhost
> docs: updated env.example of OLLAMA & LMSTUDIO base url

- app/components/settings/debug/DebugTab.tsx
- app/lib/hooks/useSettings.tsx
check for updates does not look for commit.json now
using github api to look for latest commit hash
> fix: check for updates does not look for commit.json now

- .github/scripts/generate-changelog.sh
- .github/workflows/update-stable.yml
- app/components/header/Header.tsx
- app/utils/selectStarterTemplate.ts
fix: hotfix auto select starter template works without github token
> fix: hotfix auto select starter template works without github token #release

- app/lib/modules/llm/providers/hyperbolic.ts
Changed updated Hyperbolic Settings link
from
https://hyperbolic.xyz/settings
to
https://app.hyperbolic.xyz/settings
> fix: updated hyperbolic link

- app/components/settings/connections/ConnectionsTab.tsx
- app/lib/hooks/useGit.ts
private git repo cloning works with github connections setup in settings
> fix: git private clone with custom proxy

- .github/workflows/docker.yaml
Fix the missing permissions from #1011
CC @thecodacus
> ci: fix docker image workflow permissions

- .github/workflows/docker.yaml
adding arm64 image  build for docker publish
> ci: added arm platform

- docs/docs/FAQ.md
> docs: faq docs formatting fixed

- README.md
- app/components/workbench/Preview.tsx
- app/lib/modules/llm/providers/github.ts
Before : 
Now : 
Light Mode : 
Dark Mode : 
1. **Added New Window Opening Function**
```javascript
const openInNewWindow = (size: WindowSize) => {
if (activePreview?.baseUrl) {
const match = activePreview.baseUrl.match(/^https?:\/\/([^.]+)\.local-credentialless\.webcontainer-api\.io/);
if (match) {
const previewId = match[1];
const previewUrl = `/webcontainer/preview/${previewId}`;
const newWindow = window.open(
previewUrl,
'_blank',
`noopener,noreferrer,width=${size.width},height=${size.height},menubar=no,toolbar=no,location=no,status=no`
);
}
}
};
```
2. **Added UI Controls**
```jsx
<div className="flex items-center relative">
{/* Open in new tab button */}
<IconButton
icon="i-ph:arrow-square-out"
onClick={() => openInNewWindow(selectedWindowSize)}
title={`Open Preview in …
```
> fix: for Open preview in a new tab.

- app/components/chat/Chat.client.tsx
fix auto select starter template trigger condition
> fix: auto select starter template bugfix

- app/lib/.server/llm/stream-text.ts
- app/lib/common/prompts/optimized.ts
- app/lib/common/prompts/prompts.ts
updated system Prompts to have correct indentation
> fix: updated system prompt to have correct indentations

- app/lib/modules/llm/providers/lmstudio.ts
- app/lib/modules/llm/providers/ollama.ts
- app/routes/api.models.ts
- bindings.sh
- docker-compose.yaml
- worker-configuration.d.ts
this should fix docker env variable for the time being
swap wrangler dev with express to run the docker image
> fix: docker prod env variable fix

- app/lib/modules/llm/manager.ts
- app/lib/modules/llm/providers/google.ts
- app/lib/modules/llm/providers/groq.ts
- app/routes/api.models.ts
support for dynamic models for google, and groq
> feat: added more dynamic models, sorted and remove duplicate models

- app/lib/common/prompts/optimized.ts
- app/lib/common/prompts/prompts.ts
> fix: tune the system prompt to avoid diff writing

- app/lib/modules/llm/providers/openai.ts
added dynamic models loading for openAI provider
> feat: added dynamic model support for openAI provider

- app/components/chat/BaseChat.tsx
- app/components/chat/Messages.client.tsx
- app/lib/hooks/useSnapScroll.ts
fixes auto scroll issue when AI response is being generated
> fix: auto scroll fix, scroll allow user to scroll up during ai response

- app/components/@settings/tabs/features/FeaturesTab.tsx
- pnpm-lock.yaml
1. Bug Fix : Preserve settings 
- Issue where the changes to the settings where not be preserved after a reload page of close the settings window.
> fix: bug fix New UI / Feature tab 

- app/lib/modules/llm/providers/amazon-bedrock.ts
New Claude 3.5 Sonnet v2 Anthropogenic Model
> feat: new anthropogenic model

- app/components/@settings/core/ControlPanel.tsx
- app/components/@settings/shared/components/TabManagement.tsx
- app/components/@settings/tabs/debug/DebugTab.tsx
- app/components/@settings/tabs/features/FeaturesTab.tsx
- app/components/@settings/tabs/profile/ProfileTab.tsx
- app/components/@settings/tabs/providers/local/LocalProvidersTab.tsx
- app/components/@settings/tabs/providers/local/OllamaModelInstaller.tsx
- app/components/@settings/tabs/settings/SettingsTab.tsx
- app/components/chat/BaseChat.tsx
- app/lib/hooks/useSettings.ts
- app/lib/stores/settings.ts
- app/utils/debounce.ts
Small bug fixes UI and fix for the https://github.com/stackblitz-labs/bolt.diy/issues/1329
> fix: bolt dyi UI bugfix

- app/routes/_index.tsx
Removed the settings button in the landingpage.
> fix: for remove settings icon _index.tsx

- .github/workflows/update-stable.yml
> ci: fixed bug with release notes on github release action

- app/components/chat/BaseChat.tsx
fixed https://github.com/stackblitz-labs/bolt.diy/issues/1346
> fix: openAILike api key not showing up

- .github/workflows/docker.yaml
ci: added arm64 build and build on tags, and parallel builds
> ci: added arm64 build and build on tags, and parallel builds

- .github/workflows/docker.yaml
ci: updated target for docker build to target prod template
> ci: updated target for docker build to target prod template

- app/components/@settings/tabs/connections/GithubConnection.tsx
simple fix for now to auto set git cookies anytime connects changed or loaded
> fix: git cookies are auto set anytime connects changed or loaded

- app/lib/persistence/useChatHistory.ts
- app/routes/api.git-proxy.$.ts
fix the git proxy to work with any provider
> fix: fix git proxy to work with other git provider

- app/components/chat/Chat.client.tsx
> fix: attachment not getting sent on first message if starter-template is on

- README.md
- changed git clone for pulling stable branch, not main anymore
- Removed some not needed stuff
> docs: docs README.md

- app/components/chat/BaseChat.tsx
- app/components/chat/Chat.client.tsx
- app/components/deploy/DeployAlert.tsx
- app/components/deploy/NetlifyDeploy.client.tsx
- app/components/deploy/VercelDeploy.client.tsx
- app/components/header/HeaderActionButtons.client.tsx
- app/lib/runtime/action-runner.ts
- app/lib/stores/workbench.ts
- app/routes/api.netlify-deploy.ts
- app/types/actions.ts
- vite.config.ts
This PR also includes:
- Fix a critical bug where deploys don't work in dev environment
- Extracts Netlify and Vercel deploy logic into separate components
- Move the Netlify and Vercel deployment logic from HeaderActionButtons.client.tsx into dedicated components (NetlifyDeploy.client.tsx and VercelDeploy.client.tsx) to improve code maintainability and reusability.
- Better support for various build output directories across different frameworks.
- Introduce a new `DeployAlert` interface and related components to provide visual feedback on build and deployment stages. This includes status updates for Vercel and Netlify deployments, with progress visualization and error handling. The changes enhance user experience by offering real-time updates during the deployment process.
> fix: simplify the SHA-1 hash function in netlify deploy by using the crypto module directly

- app/components/workbench/Workbench.client.tsx
> feat: consolidate sync & export items into an overflow menu

- app/components/@settings/tabs/connections/ConnectionDiagnostics.tsx
- app/components/@settings/tabs/connections/ConnectionsTab.tsx
- app/components/@settings/tabs/connections/GithubConnection.tsx
- app/components/@settings/tabs/connections/NetlifyConnection.tsx
- app/components/@settings/tabs/connections/VercelConnection.tsx
- app/components/@settings/tabs/data/DataTab.tsx
- app/components/chat/AssistantMessage.tsx
- app/components/chat/Chat.client.tsx
- app/components/workbench/Preview.tsx
- app/lib/hooks/useDataOperations.ts
- app/lib/stores/previews.ts
- Updated the disconnect button styling to match Vercel's design:
- Changed from `<Button>` component to native `<button>` element
- Added red background (`bg-red-500`) with hover effect (`hover:bg-red-600`)
- Updated icon from `i-ph:sign-out` to `i-ph:plug`
- Simplified text to just "Disconnect"
- Added connection status indicator with check-circle icon and "Connected to GitHub" text
- Implemented diagnostics for Vercel and Supabase connections
- Added new helper function `safeJsonParse` for safer JSON parsing operations
- **Vercel Diagnostics:**
- LocalStorage token verification
- API endpoint connectivity test
- Connection status validation
- Reset functionality for Vercel connection
- **Supabase Diagnostics:**
- LocalStorage credentials verification
- API endpoint connectivity test
- …
> feat: update connectiontab and datatab security fix

- app/components/chat/GitCloneButton.tsx
- app/components/git/GitUrlImport.client.tsx
- app/lib/webcontainer/index.ts
Remove redundant error type handling in webcontainer to simplify logic and improve maintainability. Additionally, comment out lock file patterns to speed up npm install process.
> refactor: optimize error handling and npm install performance

- app/components/workbench/DiffView.tsx
- app/lib/common/prompts/new-prompt.ts
- app/lib/persistence/useChatHistory.ts
- app/lib/stores/files.ts
- App/Browser freezing
- Excessive memory usage
- The issue of snapshots not deleting alongside chat
- Start commands not always being included in artifact
- 20+ Shiki instances being spawned from Diffs
- Remove redundant `_chatId` parameter in `takeSnapshot` function to ensure it uses the same ID as chats.
- Update prompt instructions for shell commands and artifact handling
- Remove redundant checks for deleted paths and streamline binary file handling. This fixes the browser using excessive memory and freezing.
- Improve DiffView to use a singleton instance of Shiki
- improve the fine-tuned system prompt to ensure start commands are returned.
> fix: various performance issues

- app/components/chat/Artifact.tsx
- app/components/chat/AssistantMessage.tsx
- app/components/chat/BaseChat.tsx
- app/components/chat/Chat.client.tsx
- app/components/chat/ChatBox.tsx
- app/components/chat/DicussMode.tsx
- app/components/chat/Markdown.tsx
- app/components/chat/Messages.client.tsx
- app/lib/.server/llm/stream-text.ts
- app/lib/common/prompts/discuss-prompt.ts
- app/lib/runtime/message-parser.ts
- app/routes/api.chat.ts
- app/utils/markdown.ts
- Implement discuss mode toggle and UI in chat box
- Add quick action buttons for file, message, implement and link actions
- Extend markdown parser to handle quick action elements
- Update message components to support discuss mode and quick actions
- Add discuss prompt for technical consulting responses
- Refactor chat components to support new functionality
The changes introduce a new discuss mode that allows users to switch between code implementation and technical discussion modes. Quick action buttons provide immediate interaction options like opening files, implement, open links etc...
> feat: add discuss mode and quick actions

- app/components/chat/AssistantMessage.tsx
- app/components/chat/BaseChat.tsx
- app/components/chat/Chat.client.tsx
- app/components/chat/ChatBox.tsx
- app/components/chat/Markdown.tsx
- app/components/chat/Messages.client.tsx
- app/components/chat/UserMessage.tsx
- app/components/chat/chatExportAndImport/ExportChatButton.tsx
- app/components/deploy/DeployButton.tsx
- app/components/header/Header.tsx
- app/components/header/HeaderActionButtons.client.tsx
- app/components/sidebar/Menu.client.tsx
- app/components/ui/ColorSchemeDialog.tsx
- app/components/workbench/Inspector.tsx
- app/components/workbench/InspectorPanel.tsx
- app/components/workbench/Preview.tsx
- app/components/workbench/Workbench.client.tsx
- app/lib/.server/llm/stream-text.ts
- app/lib/common/prompt-library.ts
- app/lib/common/prompts/new-prompt.ts
- app/lib/common/prompts/prompts.ts
- app/lib/hooks/StickToBottom.tsx
- app/lib/persistence/ChatDescription.client.tsx
- app/lib/webcontainer/index.ts
- app/routes/api.chat.ts
- app/styles/index.scss
- app/styles/variables.scss
- app/types/design-scheme.ts
- app/utils/markdown.ts
- public/inspector-script.js
- Added inspector feature in the preview - This allows selecting individual elements from the preview to instruct the agent to focus on.
- introduce a design palette feature -  This allows pre setting of color palette, typography and design elements for the agent to use throughout your project.
- Color palette uses a default base scheme that align's with bolt.diy dark mode.
- Workbench sidebar icon for hiding chat/showing full width workbench
- Workbench is now wider allowing more workspace in view.
- Chat re-design now uses the entire width of the message section for better readability.
- Added slight blur to bottom of messages to prevent the cookie cutter look.
- Refactored header to now include export dropdown(download code and chat)
> feat: add inspector, design palette and redesign

- app/lib/common/prompt-library.ts
- app/lib/common/prompts/new-prompt.ts
- Refactored the new fine-tuned system prompt to heavily reduce token usage by removing redundent snippets and duplicate instructions while keeping the same strict rules in place.
- Default prompt now uses this fine-tuned prompt to reduce token usage by default
(both using the same request of `create a react app landing page`)
> refactor: improve fine-tuned prompt to reduce token usage and set as default

- app/components/editor/codemirror/BinaryContent.tsx
- app/lib/stores/editor.ts
- Add isBinary flag to editor documents to handle binary files appropriately.
- Update BinaryContent component styling to display properly in the editor
> fix: add binary file detection support

- app/components/deploy/VercelDeploy.client.tsx
- app/lib/runtime/action-runner.ts
- app/routes/api.vercel-deploy.ts
- Implemented a function to detect project frameworks based on package.json and configuration files.
- Added support for including source files in the deployment request for frameworks that require building.
- Updated the action function to handle framework detection and adjust deployment configuration accordingly.
- Removed unnecessary console logs and improved error handling for file reading operations.
> feat: enhance Vercel deployment process with framework detection and source file handling

- app/components/chat/AssistantMessage.tsx
- app/components/chat/ToolInvocations.tsx
- Moved the Markdown rendering for content in AssistantMessage to a new position for better structure.
- Updated ToolInvocations component to enhance UI with improved spacing and keyboard shortcut handling for tool execution.
- Added state management for expanded tool details and integrated keyboard shortcuts for approving and rejecting tool calls.
> refactor(chat): streamline AssistantMessage and ToolInvocations components

- app/lib/.server/llm/stream-text.ts
- app/lib/common/prompts/new-prompt.ts
- app/lib/stores/files.ts
- app/lib/stores/previews.ts
- Introduced a `sanitizeText` function to remove specific content from messages, enhancing the integrity of the streamed text. and reducing token usage.
- Updated the `streamText` function to utilize `sanitizeText` for both user and assistant messages, ensuring consistent message formatting.
- Adjusted message processing to maintain the structure while applying sanitization.
- Remove excessive memory intensive watcher in `preview.ts`
- Add package-json.lock to excludes in `files.ts` watch
- Add condition to system prompt to include the supabase instructions based on if conditions are met.
> fix: add text sanitization function to clean user and assistant messages of new parts object

- app/components/chat/ModelSelector.tsx
- Introduced a helper function `isModelLikelyFree` to identify models that are free based on their label or name.
- Added a toggle button to filter models, allowing users to view only free models when using the OpenRouter provider.
- Updated the model filtering logic to incorporate the free models filter and adjusted the UI to reflect the count of free models found.
- Reset the free models filter when the provider changes to ensure accurate results.
> feat: add filter for free models in ModelSelector component for OpenRouter

- app/components/chat/Chat.client.tsx
- app/components/chat/Messages.client.tsx
- app/components/chat/UserMessage.tsx
- Updated UserMessage to accept a new `parts` prop for handling different message types, including images.
- Refactored image handling to extract and display images from the parts array, ensuring proper rendering of image content.
- Adjusted the layout and styling of the UserMessage component for better visual presentation.
> fix: enhance UserMessage component to support image parts and improve rendering

- app/components/chat/ToolInvocations.tsx
- Changed background classes for better visual consistency.
- Simplified the structure of ToolCallsList, enhancing readability and layout.
- Improved button styles for better user interaction and accessibility.
> refactor: update styling and structure in ToolInvocations and ToolCallsList components

- .env.example
- app/components/@settings/tabs/providers/cloud/CloudProvidersTab.tsx
- app/components/@settings/tabs/providers/service-status/provider-factory.ts
- app/components/@settings/tabs/providers/service-status/providers/moonshot.ts
- app/components/@settings/tabs/providers/service-status/types.ts
- app/components/chat/ModelSelector.tsx
- app/lib/.server/llm/constants.ts
- app/lib/.server/llm/stream-text.ts
- app/lib/modules/llm/providers/anthropic.ts
- app/lib/modules/llm/providers/github.ts
- app/lib/modules/llm/providers/google.ts
- app/lib/modules/llm/providers/moonshot.ts
- app/lib/modules/llm/providers/openai.ts
- app/lib/modules/llm/providers/perplexity.ts
- app/lib/modules/llm/providers/xai.ts
- app/lib/modules/llm/registry.ts
- app/routes/api.llmcall.ts
- vite.config.ts
This PR adds comprehensive support for Moonshot AI (Kimi) models and updates the xAI provider with the latest Grok model variants, bringing cutting-edge
AI capabilities to bolt.diy.
- **Complete Provider Integration**: Full OpenAI-compatible API support via `api.moonshot.ai`
- **11 Model Variants** including:
- **Legacy Models**: `moonshot-v1-8k/32k/128k` (8K-128K context)
- **Latest Kimi K2**: `kimi-k2-0711-preview`, `kimi-k2-turbo-preview`
- **Reasoning Model**: `kimi-thinking-preview` with advanced reasoning capabilities
- **Vision Models**: Multimodal support with `moonshot-v1-*-vision-preview` variants
- **Auto-Selection**: `moonshot-v1-auto` and `kimi-latest` for optimal model selection
- **Grok 4**: Latest flagship model with 256K context window
- **Grok 4 (07-09)**: Specific …
> feat: add Moonshot AI (Kimi) provider and update xAI Grok models

- CONTRIBUTING.md
- app/commit.json
Updated the link to issues tracker in the **CONTRIBUTING.md** guide, under "_Reporting Bugs and Feature Requests_" section. Specifically, the line that says "Check the issue tracker to avoid duplicates".
> docs: updated link to Issues Tracker in CONTRIBUTING.md.
