stackblitz-labs/bolt.diy

.env.example, app/entry.server.tsx, app/routes/api.models.ts, app/utils/constants.ts, app/utils/types.ts, worker-configuration.d.ts
with the current implementation user doesnt select custom models so I made it possible to have  user select available models
=> let the ollama models be auto generated from ollama api

app/lib/.server/llm/constants.ts
max_tokens for llama 3.1 models must be less than or equal to 8000 but it is set to 8192. just change it to 8000 and the error is fixed.
=> Fix for llama 3.1 models

app/components/workbench/Workbench.client.tsx, app/lib/stores/workbench.ts, package.json, pnpm-lock.yaml
Added Github push functionality: By pressing the button, the user will be asked for a name of a repo, his github username and his github token. 
This code is being run client side so the user will always be asked for his credentials (for security reasons).
I think the code is pretty straight forward. Let me know if you have any questions or would like any changes to the code.
=> Added GitHub push functionality

.dockerignore
This pull request adds  `.dockerignore` file to streamline the Docker build process by excluding unnecessary files and directories.
File exclusions:
node_modules
docs
logs
build
cache
=> chore: create .dockerignore file

app/lib/.server/llm/model.ts
Looks like [ollama-ai-provider](https://github.com/sgomez/ollama-ai-provider/blob/main/packages/ollama/src/ollama-chat-settings.ts#L189) support setting context length via setting `numCtx`.
We could probably expose it via ENV  if needed
https://github.com/user-attachments/assets/d0e975b7-c658-4116-a8c1-d6585656934a
=> feat: set numCtx = 32768 for Ollama models

README.md
The installation description stated to create an .env file out of the .env.example This leads to an error when executing docker compose up since the docker-compose.yml expects the environment file being called .env.local
=> docs: update README.md changed .env to .env.local

app/components/chat/Chat.client.tsx, app/lib/hooks/usePromptEnhancer.ts, app/routes/api.enhancer.ts
**Summary**  
This PR resolves two critical issues introduced in the latest repository update. These fixes enhance user experience by ensuring that both the "enhance" feature and model provider settings work as expected, improving continuity and usability.
1. **Enhance Feature Prompt Disappearance**  
- Fixed the disappearing prompt by ensuring it remains visible and processed correctly after clicking "enhance."
2. **Model Provider Setting Persistence**  
- Implemented logic to preserve the selected model provider across project reloads, maintaining user preferences.
https://github.com/user-attachments/assets/d67f0147-c4de-4b2c-9e29-9b1b291e411b
=> fix: bug  #245

app/lib/.server/llm/model.ts
Fixes the arguments passed to createGoogleGenerativeAI. It should be an object.
=> fix: gemini create model error

.env.example
localhost:11434 made its way into .env.example. This will fail for anyone attempting to use ottodev with local machine ollama.
=> Should not provide hard-coded OLLAMA_API_BASE_URL value in .env.example

app/lib/runtime/action-runner.ts, app/lib/stores/workbench.ts
This PR implements a global execution queue to ensure proper synchronization of file operations and shell commands, particularly during project reloads and code streaming. It addresses issues with command execution order and eliminates UI flickering during code streaming operations.
- Added `#globalExecutionQueue` to `WorkbenchStore` to manage sequential execution
- Implemented queue management methods to ensure operations run in correct order
- Modified action handling to respect queue ordering
- Made start actions non-blocking while maintaining execution order
- Added delay between start actions to prevent race conditions
- Improved promise chain handling in action execution
- Split action handling into public and private methods for better control
- Modified file operations to properly …
=> fix(project-reload): execution order is fix, this fixes the inconsistency on project reload

app/components/chat/Artifact.tsx, app/components/workbench/Workbench.client.tsx, app/lib/.server/llm/prompts.ts, app/lib/stores/workbench.ts, app/utils/diff.spec.ts, app/utils/diff.ts
First contribution here
I've found a topic on the thinktank forum
https://thinktank.ottomator.ai/t/ux-enhancement-ctrl-click-shortcut-in-chat-to-go-to-source-file-in-workbench/478
i wanted to start contributing small to learn the codebase and eventually do some more.
https://github.com/user-attachments/assets/341836cd-e079-4020-a949-ab5c72e5270a
Allow clicking on files ("Artifacts") in the chat to open them in the Workbench.
* Function in the Artifact class to open in workbench
* Made usage of the WORK_DIR variable in my changes
* Went a little further and replaced the variable in the codebase
* Reused a function to make filePaths relative
* Little humble test class to verify WORK_DIR Changes don't break the Regex
=> feat: [UX] click shortcut in chat to go to source file in workbench

app/utils/constants.ts
I've added all the present models from Google Gemini to the list. Did a bit of testing with exp-1114 and it works great.
=> Update the Google Gemini models list

.gitignore, app/components/chat/BaseChat.tsx
This PR includes two changes:
Enhance Chat Component Background:
Updated the BaseChat component to include a background and border styling. This resolves a visual issue where the area under the chat component appeared broken
Before:
After:
=> (Ready for review) - Small visual fix. Add background for chat window(currently transparent and looks ugly)

app/utils/constants.ts
Just saw that Google has updated their experimental model so I had to update it here as well.
=> Update to Gemini exp-1121

app/utils/logger.ts
This pull request includes a minor change to the `app/utils/logger.ts` file. The change simplifies the initialization of the `currentLevel` variable by removing unnecessary parentheses.
Before:
After:
* [`app/utils/logger.ts`](diffhunk://#diff-b86f5e26801323458e866bf027d7436e5b1cc02d839e2491ee23862ab28eae1dL14-R14): Simplified the initialization of the `currentLevel` variable by removing unnecessary parentheses.
=> fix: prettier issue

package.json, pnpm-lock.yaml
Bumps the npm_and_yarn group with 6 updates in the / directory:
| Package | From | To |
| --- | --- | --- |
| [vite](https://github.com/vitejs/vite/tree/HEAD/packages/vite) | `5.3.1` | `5.3.6` | | [cross-spawn](https://github.com/moxystudio/node-cross-spawn) | `7.0.3` | `7.0.6` | | [elliptic](https://github.com/indutny/elliptic) | `6.5.6` | `6.6.1` | | [express](https://github.com/expressjs/express) | `4.19.2` | `4.21.1` | | [micromatch](https://github.com/micromatch/micromatch) | `4.0.7` | `4.0.8` | | [rollup](https://github.com/rollup/rollup) | `4.18.0` | `4.27.4` |
Updates `vite` from 5.3.1 to 5.3.6
- [Release notes](https://github.com/vitejs/vite/releases)
- [Changelog](https://github.com/vitejs/vite/blob/v5.3.6/packages/vite/CHANGELOG.md)
- …
=> Bump the npm_and_yarn group across 1 directory with 9 updates

app/components/sidebar/Menu.client.tsx, app/lib/hooks/useSearchFilter.ts
This pull request includes several changes to the `Menu` component in the `sidebar` directory, focusing on adding a search filter functionality and improving the user interface. The most important changes include importing and utilizing a new `useSearchFilter` hook, modifying the `Menu` component to include a search input, and updating the display logic for the list of items.
Enhancements to the `Menu` component:
* [`app/components/sidebar/Menu.client.tsx`](diffhunk://#diff-ec93c6ae76ca1d8b57b3affb838760a0ba291121532e6f4b02c9b007c9ffbefcR11): Imported the `useSearchFilter` hook and added a search input field to the `Menu` component. Updated the list display logic to use the filtered list from the search filter. [[1]](diffhunk://#diff-ec93c6ae76ca1d8b57b3affb838760a0ba291121532e6f4b02c9b007 …
=> Add search chats support

app/lib/runtime/action-runner.ts, app/utils/logger.ts
When the app reloads, it re-runs all the commands, but the shell commands were failing. To fix this issue, I've made the following change in the app/lib/runtime/action-runner.ts file:
Now the actions are properly awaited
Before Change:
After Change:
Addition of the return statement before calling this.#executeAction. This ensures that the promise returned by this.#executeAction is properly awaited and propagated through the promise chain, preventing the subsequent actions from running before the current one has completed.
- ✅ Manually verified that shell commands now execute successfully during app reload
- ✅ Confirmed actions run in the correct sequence  
Note: Code changes also contains a prettier fix regarding `let currentLevel: DebugLevel = (import.meta.env.VITE_LOG_LEVEL ?? …
=> [fix]: shell commands execution failure on app reload

app/components/chat/Markdown.spec.ts, app/components/chat/Markdown.tsx, app/utils/logger.ts
When chat messages contain Artifact components (like ActionLists) wrapped in code fences (```), they are rendered as plain code blocks instead of rendering via Artifact.tsx component.
```
// ignore escapes
/`/`/`xml
<div class="__boltArtifact__" data-message-id="RVO8njc"></div>
/`/`/`
```
ReactMarkdown processes code-fenced content before component rendering, causing the __boltArtifact__ elements to be treated as plain text within code blocks rather than being passed to the Artifact component.
Added preprocessing step to remove code fence markers specifically around artifact elements:
- Introduced stripCodeFenceFromArtifact function in app/components/chat/Markdown.tsx
- Added unit tests in app/components/chat/Markdown.spec.ts
Explored handling at the component level through …
```
=> [fix]: artifact actionlist rendering in chat

app/lib/stores/workbench.ts
**Description**
This pull request introduces a new functionality that enhances the user experience when downloading ZIP files. When a user clicks the "Download ZIP" button, a prompt is displayed to allow the user to edit the filename before proceeding with the download. By default, the filename is pre-filled with a unique project name that includes a hash, ensuring uniqueness.
**Key Features**
**Pre-filled Default Filename:**
- The filename includes a unique project name (e.g., ProjectName-<unique-hash>.zip).
- The hash is generated to ensure the file name remains distinct for each project.
=> feat: add custom unique filename when download as zip

README.md, app/components/chat/Chat.client.tsx, app/utils/constants.ts
This pull request introduces key improvements to the chat component's functionality, focusing on prompt input persistence and performance optimization. By implementing cookie-based caching and debouncing techniques, we've enhanced the user experience and reduced unnecessary re-renders.
- Added a new constant `PROMPT_COOKIE_KEY` in `app/utils/constants.ts` to standardize prompt caching
- Implemented cookie-based caching to preserve user input between sessions
- Automatically restore previous prompt on component initialization
- Clear cached prompt when the chat is reset
- Integrated `debounce` utility to minimize unnecessary cache writes
- Used `useCallback` to memoize functions and prevent redundant re-renders
- Created a debounced caching mechanism for textarea input
- **Files …
=> Enhance Chat Functionality with Prompt Caching

app/components/workbench/EditorPanel.tsx, app/components/workbench/terminal/Terminal.tsx, app/components/workbench/terminal/TerminalTabs.tsx
I've detected a performance bottle neck on page load, opened the console and saw this
Before the fix the Terminal tabs would get rendered too many times.
I believe using a big function call with many inputs that change often and having a big ass interface defined underneath is an anti pattern to the framework used here, [memo](https://react.dev/reference/react/memo).
> In React, memoization is a performance optimization technique used to prevent unnecessary re-renders and recomputations. It involves caching the results of expensive function calls or component renders so that if the same inputs (parameters) occur again, the cached result is returned instead of recomputing it.
> React provides built-in hooks and higher-order components (HOCs) for memoization:
> React.memo: A higher-order …
=> BugFix: Terminal render too many times causing performance freeze

.husky/pre-commit
to better guide developers who don't lint their code prior to committing ;)
follows-up on #378
=> Update linting-failed-message in pre-commit

app/components/workbench/Preview.tsx
In this PR, I have introduced two key enhancements to the preview functionality:
1. **Fullscreen Functionality:**
A fullscreen toggle button has been added, allowing users to enter and exit fullscreen mode seamlessly. This feature provides a more immersive environment for previewing content without distractions.
2. **Responsive Mode with Resizable Width:**
Users can now switch between a responsive mode, where the preview fills the entire available space, and a device mode, where the preview is constrained to a fixed width. In device mode, two vertical handles on the left and right edges allow the user to interactively resize the preview's width, similar to the responsive mode in browser dev tools. The height remains full, ensuring a consistent vertical display.
Screenshots:
Buttons …
=> Added Fullscreen and Resizing to Preview

app/components/chat/BaseChat.tsx, app/lib/.server/llm/api-key.ts
As I was testing together AI integration noticed that it fails due to wrong API key
Investigating I found out that by default it goes to OpenAI API url and obviously fails
Turned out that reason is that by default nothing is set in env.
Made hardcoded default if env has nothing
=> (ready for review)Harcode together ai api url as fallback

app/components/editor/codemirror/languages.ts, package.json
Add vue language support (highlighting) for codemirror
=> Feat: add vue support for codemirror

app/components/settings/SettingsWindow.tsx, app/components/workbench/Workbench.client.tsx, app/lib/stores/workbench.ts
Added a connections tab, now you can enter GitHub creds and store them in cookies like the API Keys
=> feat: Connections Tabs

app/commit.json, app/lib/.server/llm/stream-text.ts, app/utils/constants.ts
Will disable context optimization and will make this experimental optional in menu in future
=> fix: removed context optimization temporarily, to be moved to optional

app/utils/constants.ts
Removed Llama3.1 70B (deprecated) and replaced it with Llama3.3-70B
=> add: Groq Llama 3.3 70B

app/utils/constants.ts
Add support for `llama-3.2-90b-vision-preview` model from Groq.
=> Add 90b llama-3.2 model for better performance

app/components/workbench/FileTree.tsx, package.json, pnpm-lock.yaml
Just `Copy path` and `Copy relative path` to start. Lays the groundwork for other context menu options (rename, delete, etc.)
https://github.com/user-attachments/assets/828a0c91-9192-4187-9aa4-284d280850a5
=> Feat: Basic file tree context menu

app/components/settings/SettingsWindow.tsx, app/components/settings/chat-history/ChatHistoryTab.tsx, app/components/settings/debug/DebugTab.tsx
Enhancement - move the connection tab below chat history in left side of settings
Enhancement - on chat tab Delete all chats now prompts you to make sure you want to
Enhancement - on the debug tab changed copy debug info from a popup to a toast notification
=> ui-ux: Setting Modal Changes

app/components/settings/providers/ProvidersTab.tsx
This fixed the icon not showing for perplexity by adding a fallback icon for providers
Before:
After:
=> ui: fallback icon for provider

README.md
Changed 'and' to '&' so that it would fit on one line.
Before:
After:
=> doc: README formating

app/utils/constants.ts
fixes the 'WARN Constants Failed to get LMStudio models:  fetch failed' error as the user most likely just has it active in provider
=> fix: warn Constants Failed 

vite.config.ts
added v3_lazyRouteDiscovery to the fvite.config.ts without any side effects. this removes the warning in terminal
=> fix: update vite.config.ts

app/components/settings/connections/ConnectionsTab.tsx
checks to make sure the entered username and token is correct before accepting it. Let you disconnect also.
=> feat: Improved GitHub connection

.github/workflows/semantic-pr.yaml, app/commit.json
Reintroducing semantic pull pr validation,
as this is a must have for better changelog system
=> chore: Reintroducing semantic pull pr validation

app/lib/hooks/useEditChatDescription.ts
added common punctuation to the charactersValid. This was because the chat titles where using some of these and when you edited the title  you would have to find these punctuation's and remove them.
=> fix: charactors to vaild list for titles

README.md
Removed the section about environment variables. In docker removed the production build. Both of these can still be found in the docs.
These changes should simplify the set up process of bolt.diy resulting in less GitHub issues being sent.
=> docs: simplified setup

README.md
Added a TOC for the README file, renamed some headings to better suite the TOC:
=> docs: added a toc for the readme

app/components/settings/providers/ProvidersTab.tsx
Made the providers list 2 columns wide to allow all to be shown at once. 
Separate out the experimental providers with a short note.
First image is with experimental providers turned off:
This image is with experimental providers turned on:
=> feat: improved providers list style

app/components/settings/data/DataTab.tsx, app/lib/runtime/message-parser.ts
Sometimes AI responds with files wrapped in markdown code block syntax, causing issues and wasting tokens. The goal is to clean this up for non-Markdown files to improve efficiency and output clarity.
- Added logic in message-parser.ts to detect and remove markdown code block syntax for non-Markdown files using regex.
- lint:fix made minor formatting and readability improvements in DataTab.tsx
https://gist.github.com/wonderwhy-er/969023d7146a5f3e3ec90ec99ba4bc4e
=> fix: detect and remove markdown block syntax that llms sometimes hallucinate for file actions

app/components/chat/Chat.client.tsx, app/components/settings/features/FeaturesTab.tsx, app/lib/.server/llm/stream-text.ts, app/lib/hooks/useSettings.tsx, app/lib/stores/settings.ts, app/routes/api.chat.ts
This PR re-enables the previously implemented context optimization feature (from PR #578) while adding a user-configurable toggle in the settings tab. This allows users to choose whether they want to use context optimization based on their specific needs and the LLM model they're using.
- Added a new switch in the Features tab for enabling/disabling context optimization
- Implemented persistent storage of the setting using cookies
- Added new state management through `enableContextOptimizationStore`
- Modified chat implementation to pass context optimization flag through the API
- Updated stream-text functionality to conditionally apply optimization
- Re-enabled previously commented out code for file content handling
- Added new `contextOptimizationEnabled` state in `useSettings` hook
- …
=> feat: redact file contents from chat and put latest files into system prompt

app/lib/modules/llm/base-provider.ts, app/lib/modules/llm/providers/lmstudio.ts, app/lib/modules/llm/types.ts
**Reason for change:**
Was testing LMStudio today based on bug report.
Was surprised that it does not work out of the box anymore.\
**What changed:**
- added baseUrl to provider configs
- made it last options after other ones are undefined
- for LMStudio added baseUrl: 'http://localhost:1234/ as that is one that LMStudio sets by default
- tested that now it works without need to change anything in LMStudio or Bolt out of the box
=> fix: add defaults for LMStudio to work out of the box

.env.example, app/lib/modules/llm/providers/hyperbolic.ts, app/lib/modules/llm/registry.ts, package.json, pnpm-lock.yaml
=> feat: added hyperbolic llm models

app/components/chat/APIKeyManager.tsx, app/components/chat/BaseChat.tsx
Reason for change:
Came up here https://github.com/stackblitz-labs/bolt.diy/pull/943
When provider has dynamic provider list that requires API key its not refreshed when you set a key
Here I made mode list refresh when keys are set
What was done:
- I separated model initialisation in to its own useEffect with apiKeys as dependency, so when they change its refreshed
- That was not enough as way we get keys always creates new object even if its the same, so use effect running in a loop
- I fixed above by making "memoizing" function that gets api keys from cookies, so if api keys did not change its same object and useEffect is not run
=> fix: refresh model list after api key changes

app/components/chat/Chat.client.tsx
handled error during starter template pull, and continue with blank template on failure
=> fix: show warning on starter template failure and continue

app/components/chat/GitCloneButton.tsx, app/components/git/GitUrlImport.client.tsx, app/components/ui/LoadingOverlay.tsx, app/lib/hooks/useGit.ts, app/routes/api.git-proxy.$.ts, app/routes/api.git-proxy.ts
**Reason for change:**
Exploring adding error messages and import progress to git import after this issue was reported
https://github.com/stackblitz-labs/bolt.diy/issues/903
Noticed that we get 403 errors from isometric git cors proxy
Also was bothered by lack of errors or progress dialog when loading.
https://github.com/user-attachments/assets/7814f655-b97e-40cf-8700-ae508b19b37b
**Changes:**
- **Git Proxy**: Implemented a custom /api/git-proxy proxy to deal with cors proxy errors for git import operations and replace isometric git one we used before, should solve 403 issues we are getting
- Added better error handling and loading overlay progress dialog to indicate import being in progress
=> fix: introduce our own cors proxy for git import to fix 403 errors on isometric git cors proxy

LICENSE
Updating copyright in LICENSE from "Copyright (c) 2024 StackBlitz, Inc." to Copyright (c) 2024 StackBlitz, Inc. and bolt.diy contributors."
@patak-dev sorry for the multiple pings, I had to correct the pull request!
=> chore: updating copyright in LICENSE

.github/workflows/docker.yaml
Created a basic container image creation pipeline.
Fix #946
Note:
You need to set a personal access token with the package permission in the secrets to publish to the github container registry.
For publishing to docker hub, you need to update the urls as well as the credentials.
=> ci: docker Image creation pipeline

Dockerfile, app/lib/modules/llm/providers/lmstudio.ts, app/lib/modules/llm/providers/ollama.ts, vite.config.ts
This PR addresses connectivity issues between the application running in Docker containers and local LLM providers (LMStudio and Ollama). It implements proper host URL resolution by replacing localhost/127.0.0.1 with host.docker.internal when running in a Docker environment.
- Added `RUNNING_IN_DOCKER=true` environment variable to Dockerfile configurations
- Implemented detection logic in provider classes to handle URL transformation
- Enhanced URL handling in LMStudio and Ollama providers
- Added proper error handling for missing base URLs
- Implemented consistent URL transformation for Docker environments
- Fixed provider settings access by correctly referencing provider-specific settings using `providerSettings?.[this.name]`
- Ensures proper configuration loading for each provider …
=> fix: ollama and lm studio url issue fix for docker and build

app/routes/api.chat.ts
Fixed real-time message streaming in production by correctly configuring Content-Type headers for Server-Sent Events (SSE).
The chat interface was experiencing inconsistent behavior between development and production environments:
- **Development (wrangler dev)**: Messages streamed correctly in real-time
- **Production**: Messages only appeared after the entire stream completed
- User experience was degraded due to lack of real-time updates
- Console logs showed chunks arriving all at once instead of streaming
Server response headers were incorrectly configured:
```typescript
// Previous configuration
return new Response(stream.readable, {
status: 200,
headers: {
contentType: 'text/plain; charset=utf-8'  // Incorrect content type
},
});
```
This caused:
- Browsers and proxies to buffer …
=> fix: streaming issue fixed for build versions

app/lib/modules/llm/base-provider.ts
Found a bug in the OpenAILike provider. It fetches the API Key as the base URL. Simple one line change.
=> fix: bugfix in fetching API Key on base llm provider

app/components/chat/APIKeyManager.tsx, app/components/chat/Chat.client.tsx, app/lib/.server/llm/stream-text.ts, app/routes/api.chat.ts, app/routes/api.check-env-key.ts, app/routes/api.enhancer.ts
some api key manager fix, the keys in UI takes priority, and enable edit even if env key is set.
added error log on llm call on server terminal
=> fix: api-key manager cleanup and log error on llm call

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/epic.md, .github/ISSUE_TEMPLATE/feature.md, PROJECT.md, README.md, app/lib/hooks/useEditChatDescription.ts
This PR documents the way we organize things (issues, PRs, ideas).
Addresses #807
=> docs: document how we work

app/components/workbench/Preview.tsx, app/lib/stores/previews.ts, app/routes/webcontainer.preview.$id.tsx
=> feat: added the "Open Preview in a New Tab"

app/components/chat/BaseChat.tsx, app/lib/api/cookies.ts, app/lib/hooks/useModels.ts, app/lib/modules/llm/manager.ts, app/routes/api.enhancer.ts, app/routes/api.llmcall.ts, app/routes/api.models.$provider.ts, app/routes/api.models.ts, app/utils/constants.ts
Up to now, some providers couldn't be configured via  the environment properly. The list of models remained empty
Previously, the list of models was retrieved from the front-end. If the list wasn't hard coded (like for many providers), the system tried to retrieve the models via the `/models` route of the provider. 
As the environment configuration which includes the API keys is intentionally not shared with the client, this request couldn't complete and failed silently on the client. 
This affected `openai like` and `openrouter` once they required api keys.
This PR implements a more robust and flexible approach to retrieving model lists by moving the initialization logic to the backend, enabling dynamic model discovery and configuration across different providers.
1. Model List Retrieval …
=> feat: configure dynamic providers via .env

CONTRIBUTING.md, README.md, docs/docs/CONTRIBUTING.md, docs/docs/index.md
docker-compose is deprecated now
=> docs: replace docker-compose with docker compose

docker-compose.yaml
Environment variables are not being passed to the container in the development profile. Adding env_file to pass them so they can be used by the application. Confirmed that this fixes the issue locally with the latest code on main.
=> fix: get environment variables for docker

app/components/chat/AssistantMessage.tsx, app/components/ui/Popover.tsx, app/entry.server.tsx, app/lib/.server/llm/constants.ts, app/lib/.server/llm/create-summary.ts, app/lib/.server/llm/select-context.ts, app/lib/.server/llm/stream-text.ts, app/lib/.server/llm/utils.ts, app/lib/modules/llm/providers/open-router.ts, app/routes/api.chat.ts, app/routes/api.check-env-key.ts, app/routes/api.enhancer.ts, app/routes/api.llmcall.ts, app/styles/variables.scss, app/types/context.ts, package.json, pnpm-lock.yaml
This PR implements intelligent context management for LLM interactions by introducing two key optimizations:
1. Code Context Optimization: Dynamically selects relevant files for the context buffer based on the current conversation
2. Chat Context Optimization: Summarizes chat history to maintain context while reducing token usage
PR attempts to solve : 
https://github.com/stackblitz-labs/bolt.diy/issues/1041
[#1042](https://github.com/stackblitz-labs/bolt.diy/issues/1042)
- Added new system for selecting relevant files using LLM analysis
- Implemented file filtering with ignore patterns similar to .gitignore
- Limited context buffer to 5 files maximum for efficient token usage
- Added support for relative and absolute file paths
- Implemented chat history summarization to compress context …
=> feat: enhance context handling by adding code context selection and implementing summary generation

app/components/chat/Markdown.tsx, app/components/chat/ThoughtBox.tsx, app/lib/modules/llm/providers/deepseek.ts, app/lib/modules/llm/providers/lmstudio.ts, app/routes/api.chat.ts, app/utils/markdown.ts, package.json, pnpm-lock.yaml
This PR introduces a collapsible thought process box component to display AI reasoning and integrates the DeepSeek AI provider. It also includes minor fixes for LM Studio provider configuration and package updates.
- Added new ThoughtBox React component for displaying AI reasoning in a collapsible format
- Integrated thought box rendering in the Markdown component
- Implemented styling using Tailwind CSS with a clean, modern design
- Integrated DeepSeek AI provider with proper SDK configuration
- Updated LM Studio provider to use correct baseURL parameter
- Updated AI-related package dependencies
Key technical implementation details:
```tsx
const ThoughtBox = ({ title, children }: PropsWithChildren<{ title: string }>) => {
const [isExpanded, setIsExpanded] = useState(false);
return (
<div …
```
=> feat: added support for reasoning content

app/components/chat/APIKeyManager.tsx, app/components/chat/Chat.client.tsx, app/lib/.server/llm/stream-text.ts, app/routes/api.chat.ts, app/routes/api.check-env-key.ts, app/routes/api.enhancer.ts
attempts to address https://github.com/stackblitz-labs/bolt.diy/issues/1103
=> fix: improve push to github option

app/lib/modules/llm/providers/groq.ts, app/utils/markdown.ts
some of the providers of deepseek is using `<think>` tag to stream thinking token directly in the response.
this PR detects that and enclose that inside a container for better user experience 
example provider `Groq`, `ollama` with deepseek models
=> feat: support for <think></think> tags to allow reasoning tokens formatted in UI

app/components/git/GitUrlImport.client.tsx, app/utils/folderImport.ts, app/utils/projectCommands.ts
solves the issue 
https://github.com/stackblitz-labs/bolt.diy/issues/1180
https://github.com/stackblitz-labs/bolt.diy/issues/1144
=> fix: issue with alternate message when importing from folder and git

app/components/chat/Messages.client.tsx
Fix for chat response auto scroll :
- More reliable auto-scrolling during streaming
- Better handling of user scroll interactions
- Improved mobile device support
- Smoother initial load with instant scroll
- Cleaner code organization and maintainability
The changes can be verified by:
1. Loading chat - should instantly scroll to bottom
2. Streaming messages - should smoothly auto-scroll
3. Manual scroll up - should stay at user's position
4. Scroll to bottom - should resume auto-scroll
5. Mobile testing - should work with touch interactions
=> fix: chat response auto scroll

app/components/chat/ModelSelector.tsx
This Pull Request updates the ModelSelector component to replace the traditional dropdown UI for selecting models with a searchable and keyboard-navigable dropdown menu. The changes aim to improve usability by providing enhanced search and navigation capabilities.
- Added state and refs:
Introduced state variables for managing the search query, dropdown state, and keyboard navigation.
Added refs for handling search input focus and tracking dropdown options.
- Implemented searchable dropdown:
Users can now filter models by typing in a search box.
Models are dynamically filtered based on provider and search criteria.
- Added keyboard navigation:
Arrow keys support navigating between filtered models.
Other key events (Enter, Escape, Tab) provide improved dropdown interaction.
- Replaced …
=> feat: implement llm model search

app/components/chat/GitCloneButton.tsx
When git cloning an astro project, all `.astro` files as well as the astro config file `astro.config.mjs` are skipped and becomes a broken project that is no longer previewable.
=> fix: broken astro project git clone

app/components/chat/Chat.client.tsx, app/components/chat/UserMessage.tsx, app/lib/hooks/useMessageParser.ts, app/lib/stores/files.ts, app/lib/stores/workbench.ts, app/utils/fileUtils.ts
This PR implements a mechanism to persist user file modifications across reload by automatically capturing all file changes and embedding them as artifacts in the next user message. These artifacts are invisible to users but contain all necessary file change data. Critically, the message parser has been extended to process both assistant AND user messages (previously only processed assistant messages), ensuring these file change artifacts are executed upon reload, reconstructing the user's file modifications.
- **Automatic capture**: System now captures any file changes made by the user
- **Artifact generation**: Added `filesToArtifacts` utility to convert these modified files into a structured artifact format
- **Artifact attachment**: Automatically prepends these file artifacts to the …
=> feat: make user made changes persistent after reload

app/components/@settings/tabs/connections/GithubConnection.tsx
the PR added back the environment variable for github token and fixed the starter template rate limit even after setting up connections in the settings  
reported https://github.com/stackblitz-labs/bolt.diy/issues/1380
=> fix: git connection fix for starter template

app/components/@settings/tabs/connections/components/RepositorySelectionDialog.tsx
fix for gitclone fails when repo does not have "main" branch for example if the repo has "master" instead of "main" branch
=> fix: git clone modal to work with non main as default branch

app/lib/modules/llm/providers/anthropic.ts
- Added support for the new Claude 3.7 Sonnet model to the Anthropic provider
- Updated model listings to include the latest Claude offerings
- Maintained consistent token limit specification for all Claude models
This PR adds support for Anthropic's newest Claude 3.7 Sonnet model (`claude-3-7-sonnet-20250219`), which provides enhanced capabilities over previous Claude versions. The model is now available in the static models list with appropriate configurations.
The update maintains the existing pattern for model configuration with 8000 tokens as the maximum allowed, consistent with other Claude models in the application. This ensures that users can seamlessly work with the new model following the same patterns as with other Claude models.
- Verified that the new model appears correctly …
=> feat(llm): add Claude 3.7 Sonnet model and update API key reference

.github/workflows/electron.yml
@leex279
added write permission for the electron github action to create a release.
manual trigger will create a draft release that’s only visible to repo members.
disable mac build for now.
see [this PR](https://github.com/stackblitz-labs/bolt.diy/pull/1136).
=> ci: give electron action permission

app/components/workbench/FileTree.tsx, app/lib/stores/files.ts, app/lib/stores/workbench.ts
File/Folder Operations:
- Rename functionality with inline editing
- Create new files and folders with proper directory structure
- Delete files and folders with confirmation dialog
- All operations update the file tree state and handle errors appropriately
Drag and Drop Image Support:
- Accepts image files via drag and drop
- Converts images to base64 format for storage
- Shows success/error notifications for uploads
- Maintains proper file structure when dropping images
UI Improvements:
- Inline rename input replaces the file/folder name during editing
- Context menu for all file operations
- Visual feedback during drag and drop
- Toast notifications for operation status
=> feat: add ability to edit/add/delete files in the file tree

app/lib/.server/llm/stream-text.ts
This is a bugfix for : https://github.com/stackblitz-labs/bolt.diy/issues/1575
Fixed a critical error where chat initialization would fail with:
`Invalid prompt: messages must be an array of CoreMessage or UIMessage`
This occurred when:
- Processing XML template selections
- Handling multimodal content (text + images)
- Receiving message content without proper type formatting
- Added validation for multimodal content format
- Ensured all content items have required `type` field
- Implemented error recovery to handle malformed messages
- Added safeguards against null/undefined values
- Created fallback mechanism for edge cases
These changes ensure compatibility with the Vercel AI SDK requirements while maintaining existing functionality.
=> fix: update stream-text.ts

.github/workflows/electron.yml
Three ways to trigger a release
manually -> release, you can choose a tag name when trigger or it will use github ref name
branch push -> draft release, this is for quick testing
tags -> release, based on the new git tag
cc: @leex279
=> ci: only draft release for branch build

app/components/@settings/tabs/connections/ConnectionsTab.tsx, app/components/sidebar/HistoryItem.tsx, app/components/sidebar/Menu.client.tsx, app/components/ui/Checkbox.tsx
This is new feature request from : https://github.com/stackblitz-labs/bolt.diy/issues/1585
feat(sidebar): Implement bulk chat deletion
Adds the ability for users to select multiple chats from the history sidebar and delete them in bulk.
**Key Changes:**
*   **Selection Mode:** Introduced a selection mode toggled by a dedicated button next to "Start new chat".
*   **Checkboxes:** Added checkboxes to each `HistoryItem` visible only when selection mode is active.
*   **Bulk Actions:** Added "Select All" / "Deselect All" and "Delete Selected" buttons (`Button` component with `ghost` variant) that appear above the chat list in selection mode.
*   **Confirmation Dialog:** Implemented a confirmation dialog (`Dialog` component) to prevent accidental deletion, listing the chats selected for …
=> feat: bulk delete chats from sidebar

app/components/chat/GitCloneButton.tsx
Vue and Svelte projects would otherwise have their `.vue` and `.svelte` files skipped when doing a git import.
=> fix: whitelist vue and svelte files

app/components/deploy/NetlifyDeploy.client.tsx, app/components/deploy/VercelDeploy.client.tsx, app/routes/api.vercel-deploy.ts
Remove redundant success toast messages from Vercel and Netlify deploy components. Additionally, prioritize the public domain URL over the private domain in the Vercel deploy action for consistency and clarity.
=> refactor: remove success toast and prioritize public domain URL

app/lib/stores/previews.ts, package.json, pnpm-lock.yaml
Fix a critical bug where npm actions fail/crash due to all file contents being included in watcher.
Update the file watch paths in the previews store to only include relevant file types (e.g., HTML, CSS, JS) and exclude unnecessary directories (e.g., node_modules, dist). This reduces unnecessary file system events and improves performance.
Also, update the @webcontainer/api dependency to the latest internal version for enhanced functionality, node20 and upcoming features.
=> fix: optimize file watch paths for preview updates and fix npm crashes

app/components/workbench/Workbench.client.tsx
Changed the `File Changes` button on the `Diff` tab to have a consistent style with the buttons on the `Code` tab. The larger font size of `File Changes` and border on the button caused the header to have an inconsistent height, which is now fixed.
`Code` tab:
Changed to:
Previously:
=> fix: make diff button consistent with other toolbar buttons

app/components/workbench/Workbench.client.tsx, package.json, pnpm-lock.yaml
update to latest version of webcontainer (1.6.1-internal.1)
fix: make diff button consistent with other toolbar buttons originally fixed in PR #1601 but had been overwritten.
https://github.com/stackblitz-labs/bolt.diy/pull/1601#issue-2973760838
=> chore: update @webcontainer/api to version 1.6.1-internal.1

.github/workflows/electron.yml, electron-builder.yml
The code signing credentials for macOS were removed from the GitHub Actions workflow and the identity field in the electron-builder.yml was set to null. This change was made to include unsigned .dmg releases
=> ci: remove macOS code signing credentials from workflow

app/components/editor/codemirror/CodeMirrorEditor.tsx, app/components/workbench/Search.tsx
When clicking on search results, the application would crash with an error: "Invalid line number 11 in 4-line document". This happened because the search results contained line numbers that were outside the range of the actual document.
1. Added safety checks in `CodeMirrorEditor.tsx` to verify that line numbers are valid before trying to navigate to them
2. Added error handling to prevent crashes when invalid line numbers are encountered
3. Adjusted line numbers in the Search component from 1-based (search API) to 0-based (editor expects)
The key improvement was adding validation to ensure we never try to navigate to a line that doesn't exist in the document, which prevents the application from crashing.
=> fix: invalid line number error in search functionality

Dockerfile
The Docker build process was failing with an out-of-memory error during the `pnpm run build` step in the `bolt-ai-production` stage.
This commit increases the memory available to Node.js by modifying the build command to include the `--max-old-space-size=4096` flag. This provides 4GB of memory to the Node.js process, which should be sufficient to complete the build.
=> fix: increase Node.js memory limit in Docker build

app/components/deploy/DeployButton.tsx, app/components/deploy/GitHubDeploy.client.tsx, app/components/deploy/GitHubDeploymentDialog.tsx
This PR adds a new GitHub deployment feature allowing users to deploy projects directly to GitHub repositories.
Features:
- Add GitHub deployment option in the deployment dropdown menu
- Create GitHubDeploy component to handle the build process
- Implement GitHubDeploymentDialog for repository selection and creation
- Support both new and existing GitHub repositories
- Allow choosing between public and private repositories
Implementation Details:
- Build projects before deploying to GitHub
- Properly format file paths for GitHub API compatibility
- Initialize new repositories with README and .gitignore files
- Implement robust error handling and user feedback
- Add detailed logging for debugging
Testing:
- Manually tested the full deployment workflow
- Verified successful creation of both …
=> feat: add GitHub deployment functionality

app/components/deploy/DeployButton.tsx, app/components/deploy/GitHubDeploy.client.tsx, app/components/deploy/GitHubDeploymentDialog.tsx, app/components/workbench/Workbench.client.tsx
This PR improves upon the GitHub deployment functionality introduced in PR #1904 by removing redundant sync features, fixing code quality issues, and providing a cleaner, more professional user experience.
- **Eliminated "Push to GitHub" sync button** from the Workbench dropdown menu
- **Removed duplicate sync pathway** that bypassed proper deployment workflow  
- **Cleaned up unused imports and state variables** (`PushToGitHubDialog`, `isPushDialogOpen`)
- **Streamlined user interface** by consolidating GitHub deployment options
- **Fixed 92+ ESLint errors** across GitHub deployment components
- **Resolved Prettier formatting issues** throughout the codebase
- **Fixed TypeScript unused variable errors**
- **Improved code organization** and removed dead code
- **Enhanced error handling** …
=> feat: github deployment cleanup

app/lib/.server/llm/constants.ts, app/lib/.server/llm/stream-text.ts, app/lib/modules/llm/providers/anthropic.ts, app/lib/modules/llm/providers/google.ts, app/lib/modules/llm/providers/groq.ts, app/lib/modules/llm/providers/open-router.ts, app/lib/modules/llm/providers/openai.ts, app/lib/modules/llm/providers/together.ts, app/routes/api.chat.ts
- ❌ **Invalid JSON Response Errors** - AI SDK streaming failures causing malformed responses
- ❌ **Token Limit API Rejections** - Models hitting API limits due to incorrect configurations
- ❌ **Outdated Model Configurations** - Static models with severely underestimated token limits
- ❌ **Poor Error Messages** - Generic errors that didn't help users troubleshoot
1. **Incorrect Token Limits**: Models configured with 8k limits instead of actual 128k-2M context windows
2. **Streaming Error Handling**: Insufficient error detection in AI SDK response processing
3. **Model Validation**: No validation of model capabilities before API calls
4. **Static Model Bloat**: 40+ hardcoded models causing maintenance overhead
---
Updated all providers with their actual context window capabilities:
| …
=> fix: token limits & Invalid JSON Response Errors

app/lib/.server/llm/constants.ts, app/lib/.server/llm/stream-text.ts, app/lib/modules/llm/providers/anthropic.ts, app/lib/modules/llm/providers/cohere.ts, app/lib/modules/llm/providers/deepseek.ts, app/lib/modules/llm/providers/github.ts, app/lib/modules/llm/providers/google.ts, app/lib/modules/llm/providers/groq.ts, app/lib/modules/llm/providers/mistral.ts, app/lib/modules/llm/providers/openai.ts, app/lib/modules/llm/providers/together.ts, app/lib/modules/llm/types.ts, app/routes/api.llmcall.ts
Fix maxCompletionTokens Implementation for All Providers
- Cohere: Added maxCompletionTokens: 4000 to all 10 static models
- DeepSeek: Added maxCompletionTokens: 8192 to all 3 static models
- Groq: Added maxCompletionTokens: 8192 to both static models
- Mistral: Added maxCompletionTokens: 8192 to all 9 static models
- Together: Added maxCompletionTokens: 8192 to both static models
- Groq: Fixed getDynamicModels to include maxCompletionTokens: 8192
- Together: Fixed getDynamicModels to include maxCompletionTokens: 8192
- OpenAI: Fixed getDynamicModels with proper logic for reasoning models (o1: 16384, o1-mini: 8192) and standard models
=> fix: maxCompletionTokens Implementation for All Providers

app/routes/api.github-template.ts
The GitHub template API was failing with a 403 Forbidden error when trying to fetch templates like `xKevIsDev/vanilla-vite-template`. The issue was caused by an environment variable name mismatch between what the API expected (`GITHUB_TOKEN`) and what was configured in the environment (`VITE_GITHUB_ACCESS_TOKEN`).
Updated the GitHub template API to support both environment variable naming conventions for better compatibility:
```typescript
// Before - only supported GITHUB_TOKEN
const githubToken = context?.cloudflare?.env?.GITHUB_TOKEN || process.env.GITHUB_TOKEN;
// After - supports both naming conventions
const githubToken = context?.cloudflare?.env?.GITHUB_TOKEN || process.env.GITHUB_TOKEN || process.env.VITE_GITHUB_ACCESS_TOKEN;
```
- **File**: `app/routes/api.github-template.ts`
- …
=> fix: template authentication issue

app/lib/hooks/useMessageParser.ts, app/lib/runtime/enhanced-message-parser.ts
Fixes #1797 - Code outputs to chat instead of creating workspace files
This PR delivers a comprehensive solution to the critical issue where certain AI models (particularly Claude 3.7 and DeepSeek) output code directly to the chat interface instead of creating files in the workspace. After extensive analysis and testing, I've implemented an enhanced message parser that intelligently detects code blocks and automatically wraps them in the proper artifact tags.
Users reported that when using Claude 3.7, DeepSeek, and other models, generated code would appear as text in the chat instead of creating actual files. This disrupted the development workflow and made it impossible to work on larger projects effectively.
Created `EnhancedStreamingMessageParser` that extends the existing parser with …
=> fix: resolve code output to chat instead of files

docker-compose.yaml, docs/docs/CONTRIBUTING.md, docs/docs/index.md, scripts/setup-env.sh
This PR fixes issue #1827 where `.env.local` file was not being properly loaded when running bolt.diy with Docker Compose.
Users reported that environment variables defined in `.env.local` were not being picked up by Docker containers, causing API keys and other configuration to not work. The issue was that Docker Compose expects a `.env` file for variable substitution in the `docker-compose.yaml` file, but the documentation instructs users to use `.env.local`.
1. **Updated `docker-compose.yaml`** to load both `.env` and `.env.local` files using array syntax
2. **Created `scripts/setup-env.sh`** helper script to automatically sync `.env.local` to `.env`
3. **Updated documentation** with clear instructions for Docker users
4. **Maintains backward compatibility** with existing setups
- 📝 …
=> fix: resolve .env.local not loading in docker compose

app/components/workbench/terminal/Terminal.tsx, app/components/workbench/terminal/TerminalManager.tsx, app/components/workbench/terminal/TerminalTabs.tsx
Fixes #1743 - Terminal becomes unresponsive after extended use
This PR delivers a production-grade solution to the terminal unresponsiveness issues that have been affecting users during extended coding sessions. After extensive investigation and testing, I've implemented a comprehensive fix that not only resolves the immediate problem but also prevents future occurrences through proactive monitoring and recovery mechanisms.
- Real-time health checks every 5 seconds to detect frozen terminals
- Activity tracking with 30-second inactivity threshold
- Automatic recovery with progressive retry strategies (up to 3 attempts)
- Graceful degradation with clear user notifications
- Robust error handling around all terminal operations
- Retry logic for addon loading failures  
- Automatic restart …
=> fix: resolve terminal unresponsiveness and improve reliability

app/lib/runtime/message-parser.ts
Implements comprehensive Save All functionality with auto-save capabilities as requested in #932
This PR introduces a professional-grade Save All system with auto-save functionality, providing users with powerful file management capabilities. The implementation includes visual feedback, keyboard shortcuts, and configurable auto-save settings.
- Prominent button in the workbench toolbar
- Visual states for unsaved files with gradient backgrounds
- File count badge showing number of unsaved files
- Keyboard shortcut support (Ctrl+Shift+S / Cmd+Shift+S)
- Beautiful animations and transitions
- Responsive design for all screen sizes
- Configurable auto-save intervals (10s to 5m)
- Visual countdown timer showing time until next save
- Smart saving based on file changes
- Toast notifications …
=> fix: auto-detect and convert code blocks to artifacts when missing tags

.depcheckrc.json, .env.example, .github/CODEOWNERS, .github/actions/setup-and-build/action.yaml, .github/workflows/ci.yaml, .github/workflows/docker.yaml, .github/workflows/electron.yml, .github/workflows/pr-release-validation.yaml, .github/workflows/preview.yaml, .github/workflows/quality.yaml, .github/workflows/security.yaml, .github/workflows/test-workflows.yaml, .github/workflows/update-stable.yml, .lighthouserc.json, app/components/@settings/core/ControlPanel.tsx, app/components/@settings/core/constants.ts, app/components/@settings/core/types.ts, app/components/@settings/tabs/bug-report/BugReportTab.tsx, app/routes/api.bug-report.ts, package.json, playwright.config.preview.ts, test-workflows.sh, tests/preview/smoke.spec.ts, vite.config.ts
This PR introduces comprehensive enhancements to the GitHub CI/CD workflows with extensive testing validation.
- **Fixed CI/CD branch reference**: Updated from `master` to `main`
- **Enabled ESLint checks**: Uncommented and activated in CI workflow  
- **Standardized tool versions**: Node.js (20.18.0) and pnpm (9.14.4) across all workflows
- **Updated GitHub Actions**: Upgraded to latest versions (cache@v4, etc.)
- **GitHub CodeQL analysis** for JavaScript/TypeScript
- **Dependency vulnerability scanning** with pnpm audit
- **SBOM generation** for supply chain security
- **Secrets detection** with Trivy scanner
- **Automated SARIF uploads** to GitHub Security tab
- **Trivy vulnerability scanning** integrated into Docker workflow
- **Security results** automatically uploaded to GitHub …
=> feat: comprehensive GitHub workflow improvements with security & quality enhancements

app/components/chat/chatExportAndImport/ExportChatButton.tsx, app/components/header/HeaderActionButtons.client.tsx, app/components/workbench/Workbench.client.tsx
- Move Export and Sync buttons from header to workbench editor panel
- Position buttons in front of Toggle Terminal button
- Standardize button styling with consistent:
* Accent colored background and white text
* Same padding (px-3 py-1.5) and font size (text-xs)
* Consistent border styling and hover states
- Fix font size conflicts by removing parent text-sm classes
- Clean up unused imports and fix prettier formatting
- Ensure dropdown items have consistent text-sm font size
Resolves button styling inconsistencies and improves UX
=> feat: move export/sync buttons to workbench and standardize styling

electron/main/ui/window.ts, package.json, scripts/electron-dev.mjs
- Add electron-dev.mjs script for hot-reload development
- Support automatic Electron dependency building
- Start Remix dev server and Electron app concurrently
- Add proper process management and cleanup
- Fix preload script path for development mode
- Add electron:dev and electron:dev:inspect npm scripts
This enables developers to run 'pnpm electron:dev' for a complete hot-reload development experience with automatic rebuilding and process management.
=> feat: add Electron hot-reload development mode
